id: A96F4ADFA
title: Brief Dzogchen Lineage Prayer
type: translation
pechas:
- I864D0608
- I0144D24D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:09:03.196552
  last_modified_at: 2023-01-04 13:09:03.196557
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I864D0608/965C: '6689'
  I0144D24D/3588: '6689'
